### ISSUE TITLE
Waveform background; flashes with other buffer content on Library resize

### ISSUE THREAD

**Issue by mxmilkiib** [mixxxdj/mixxx#12706]
### Bug Description

When I resize the Library, it's a bit slow and the waveform area background flashes with snippets of windows and apps from other desktops.

This is an Optumus laptop, but just running with Nvdia all the time because the hybrid mode ******* **** freezes all screens when there's too much activity (like minimising and reopening mpv to quickly... Ugh.

```
Graphics:
  Device-1: Intel HD Graphics 530 driver: i915 v: kernel
  Device-2: NVIDIA GM107GLM [Quadro M2000M] driver: nvidia v: 545.29.06
  Device-3: Bison ThinkPad P50 Integrated Camera driver: uvcvideo type: USB
  Display: server: X.Org v: 21.1.11 with: Xwayland v: 23.2.4 driver: X:
    loaded: modesetting,nvidia dri: iris gpu: i915,nvidia,nvidia-nvswitch
    resolution: 1: 1920x1080~60Hz 2: 1920x1080~60Hz
  API: EGL v: 1.5 drivers: iris,nvidia,swrast
    platforms: gbm,x11,surfaceless,device
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: nvidia mesa v: 545.29.06
    renderer: Quadro M2000M/PCIe/SSE2
  API: Vulkan v: 1.3.274 drivers: nvidia surfaces: xcb,xlib
```
I haven't gotten around to building 2.4-beta yet...

### Version

2.5-alpha
